### ISSUE TITLE
cobbler import --path=rsync:// fails because of wrong conversion to absolute path

### ISSUE THREAD

**Issue by jfschneider** [cobbler/cobbler#1767]
Centos 7, cobbler-2.8.0-4.el7.x86_64 from epel.
Problem:
cobbler import --path rsync://mirrorserver/distro-rhel72-x86_64/ --arch=x86_64  --name=rhel72
fails with 'Command failed'.
from the log:
```
 INFO | import_tree; ['/rsync:/mirrorserver/ks_mirror/rhel72-x86_64', 'rhel72', None, None, None]
 INFO | running: rsync -a  '/rsync:/mirrorserver/ks_mirror/rhel72-x86_64/' /var/www/cobbler/ks_mirror/rhel72-x86_64 --progress
```
the rsync://-URL is interpreted as a relative path and gets 'fixed'
I am no python programmer, but after changing in **cli.py** at action "import":
```
517c517
<             if options.path:
---
>             #if options.path:
519c519
<                 options.path = os.path.abspath(options.path)
---
>                 #options.path = os.path.abspath(options.path)
```

rsync-Url mirroring works. Althoug I guess that now relative paths don't get fixed, would need something like `if options.path && ! options.path.match(/rsync:/)` or whatever that is in python.

**Comment by jmaas** [comment]
confirmed :( thanks for reporting!

**Comment by jmaas** [comment]
Fixed in #1799

**Comment by qtlin** [comment]
I just tried 2.8.1 from latest epel and it has the same problem.

**Comment by wsanders** [comment]
Hasn't quite squeaked into the Centos cobbler-2.8.2-1.el7.x86_64 rpm in centos/epel 7 repo but the patch in the description works.

**Comment by neskweek** [comment]
I am currently using v2.8.2-1.el7 from EPEL and this is not solved:

```
cobbler import --name=Base --arch=x86_64 --path rsync://root@10.9.70.102:/var/www/html/Base/

Tue Jun  5 19:16:42 2018 - INFO | import_tree; ['/rsync:/root@10.9.70.102:/var/www/html/Base', 'Base', None, None, None]
Tue Jun  5 19:16:42 2018 - INFO | importing from a network location, running rsync to fetch the files first
Tue Jun  5 19:16:42 2018 - INFO | running: rsync -a  '/rsync:/root@10.9.70.102:/var/www/html/Base/' /var/www/cobbler/ks_mirror/Base-x86_64 --progress
```
