### ISSUE TITLE
Cobbler-3.2 reposync Failed

### ISSUE THREAD

**Issue by asimat** [cobbler/cobbler#2519]
### Describe the bug

cobbler reposync task fails

I am using CentOS-8.3 - minimum install - with fresh Cobbler-3.2 installed.

First part of reposync I managed to fix, the second part of the task runs python scripts which I don't understand 

First part runs a command: /usr/bin/dnf reposync -n -d .....  --> this I fixed easily as below:

The -d no longer works under CentOS-8, its now --delete. This behaviour can be changed from /etc/cobbler/settings. 

So technically reposync is working/syncing, but the second part of the command/script throws errors which I have added at the end.

### To Reproduce

1. Run: 'cobbler reposync --only="epel-8-modular"
4. See error: End with !!! TASK FAILED !!!

### Expected behavior

Task should complete successfully

### Version

Cobbler 3.2.0

### Screenshots
cobbler reposync --only="epel-8-modular"
task started: 2021-01-17_023951_reposync
task started (id=Reposync, time=Sun Jan 17 02:39:51 2021)
running python triggers from /var/lib/cobbler/triggers/task/reposync/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/reposync/pre/*
shell triggers finished successfully
hello, reposync
run, reposync, run!
creating: /var/www/cobbler/repo_mirror/epel-8-modular/config.repo
creating: /var/www/cobbler/repo_mirror/epel-8-modular/.origin/epel-8-modular.repo
running: /usr/bin/dnf reposync -n --delete --config=/var/www/cobbler/repo_mirror/epel-8-modular/.origin/epel-8-modular.repo --repoid=epel-8-modular -p /var/www/cobbler/repo_mirror -a x86_64
3.0 kB     00:00
[SKIPPED] 389-ds-base-1.4.3.17-1.module_el8+10764+2b5f8656.x86_64.rpm: Already downloaded
[SKIPPED] 389-ds-base-1.4.4.9-1.module_el8+10763+39cf6b48.x86_64.rpm: Already downloaded
[SKIPPED] 389-ds-base-2.0.1-1.module_el8+10522+e95198da.x86_64.rpm: Already downloaded
[SKIPPED] 389-ds-base-devel-1.4.3.17-1.module_el8+10764+2b5f8656.x86_64.rpm: Already downloaded
.
.
.
[SKIPPED] zabbix-server-mysql-5.0.3-1.module_el8+10819+75196edd.x86_64.rpm: Already downloaded
[SKIPPED] zabbix-server-pgsql-5.0.3-1.module_el8+10819+75196edd.x86_64.rpm: Already downloaded

received on stderr:
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'yum/librepo is required to use this feature'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/utils.py", line 100, in die
    raise CX(msg)

Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'yum/librepo is required to use this feature'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/actions/reposync.py", line 169, in run
    self.sync(repo)

  File "/usr/lib/python3.6/site-packages/cobbler/actions/reposync.py", line 212, in sync
    self.yum_sync(repo)

  File "/usr/lib/python3.6/site-packages/cobbler/actions/reposync.py", line 611, in yum_sync
    utils.die(self.logger, "yum/librepo is required to use this feature")

  File "/usr/lib/python3.6/site-packages/cobbler/utils.py", line 108, in die
    raise CX(msg)

reposync failed, tries left: 0
reposync failed, retry limit reached, skipping
running: chown -R root:apache /var/www/cobbler/repo_mirror/epel-8-modular
received on stdout:
received on stderr:
running: chmod -R 755 /var/www/cobbler/repo_mirror/epel-8-modular
received on stdout:
received on stderr:
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'overall reposync failed, at least one repo failed to synchronize'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/utils.py", line 100, in die
    raise CX(msg)

Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'overall reposync failed, at least one repo failed to synchronize'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 98, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 330, in runner
    name=name, nofail=nofail, logger=self.logger)

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1373, in reposync
    action_reposync.run(name)

  File "/usr/lib/python3.6/site-packages/cobbler/actions/reposync.py", line 197, in run
    utils.die(self.logger, "overall reposync failed, at least one repo failed to synchronize")

  File "/usr/lib/python3.6/site-packages/cobbler/utils.py", line 108, in die
    raise CX(msg)

!!! TASK FAILED !!!

### Additional context

Managed to fix the reposync command itself by swapping -d with --delete (i think I also removed -l). the post scripts linked to reposync seem to be failing. This is failing on Cobbler 3.2 running on CentOS 8.3. 

(I have a second system running Cobbler 2.8.5 on CentOS 7.9 which works fine).

**Comment by asimat** [comment]
Is there a temp fix for reposync ? any files I can download and replace ?

Is there something I can run manually so it cleanly updates the repo. Right now the scripts that run after reposync are failing and leaving the repo in some unusable state.

**Comment by asimat** [comment]
FIXED !!! needs: yum install python3-librepo

needs: python3-librepo  --> the error message says 'yum/librepo is required to use this feature'

yum install python3-librepo
service cobblerd restart
cobbler sync

Reposync then works fine.

I guess the package installer needs to force install this package. Its probably mentioned as a requirement somewhere - but as I installed from rpm, so was expecting all required packages to be installed.

**Comment by SchoolGuy** [comment]
@asimat The specfile sets a `Recommends`, meaning it won't install it per default but I agree that this error message needs to be improved or we need to change this to a `Require`. At least we need to document the error messages better in Cobbler... So much to do... XD

**Comment by manoj0772** [comment]
@asimat Is there anyway i can see the flags you are using in  /etc/cobbler/settings.yaml file for reposync. I added below 2nd line which didn't exists before and i am using same version Cobbler 3.2.2 but i still get the same error as it tried to use 
"running: /usr/bin/dnf reposync -l -m -d --config" . I did ran cobbler sync and restart after my change. 

[manpat1@psappl165 cobbler]$ grep reposync /etc/cobbler/settings.yaml
reposync_rsync_flags: "-rltDv --copy-unsafe-links"
reposync_flags: "-n --delete"
[manpat1@psappl165 cobbler]$
